// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUXB1TQ6Yy8Fxe_HpgFb95ZpwTCYzWgkg',
    appId: '1:19991173878:web:14e23c3cbb9c44f46faad7',
    messagingSenderId: '19991173878',
    projectId: 'lawtus-d033f',
    authDomain: 'lawtus-d033f.firebaseapp.com',
    storageBucket: 'lawtus-d033f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKM1Xay-tjMQe0GUzQ3oQH2O3DTzZ9Mso',
    appId: '1:19991173878:android:53adbb41da6702186faad7',
    messagingSenderId: '19991173878',
    projectId: 'lawtus-d033f',
    storageBucket: 'lawtus-d033f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJOaxnGDqoGrV-3D6GvWyl50VE8gUquYQ',
    appId: '1:19991173878:ios:913deb08ffa5e0126faad7',
    messagingSenderId: '19991173878',
    projectId: 'lawtus-d033f',
    storageBucket: 'lawtus-d033f.firebasestorage.app',
    iosBundleId: 'com.example.lawtustutor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJOaxnGDqoGrV-3D6GvWyl50VE8gUquYQ',
    appId: '1:19991173878:ios:913deb08ffa5e0126faad7',
    messagingSenderId: '19991173878',
    projectId: 'lawtus-d033f',
    storageBucket: 'lawtus-d033f.firebasestorage.app',
    iosBundleId: 'com.example.lawtustutor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUXB1TQ6Yy8Fxe_HpgFb95ZpwTCYzWgkg',
    appId: '1:19991173878:web:0069443865d312376faad7',
    messagingSenderId: '19991173878',
    projectId: 'lawtus-d033f',
    authDomain: 'lawtus-d033f.firebaseapp.com',
    storageBucket: 'lawtus-d033f.firebasestorage.app',
  );
}
